# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) 2022, Michael Herwig <contact@michael-herwig.de>
name: Build, Test & Analyze
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc10, clang12]
        arch: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "devenv/requirements.txt"
      - name: Install Python Packages
        run: pip install -r devenv/requirements.txt
      - name: Configure BuildSystem
        env:
          CMAKE_TOOLCHAIN_FILE: "${{ github.workspace }}/cmake/presets/linux-${{ matrix.compiler }}-${{ matrix.arch }}.cmake"
          CI_HUNTER_TOKEN: ${{ secrets.CI_HUNTER_TOKEN }}
        run: |
          cmake --preset gha-release
          cmake --preset gha-debug
      - name: Build
        run: |
          cmake --build --preset gha-release
          cmake --build --preset gha-debug
      - name: Test
        run: |
          ctest --preset gha-release
          ctest --preset gha-debug
